### ISSUE TITLE
Upgrade to 11.0 SP9

### ISSUE THREAD

**Issue by cgillis-aras** [ArasLabs/aras-send-to#1]
This needs to be tested against 11.0 SP9 and upgraded if necessary.

**Comment by AngelaIp** [comment]
Surprise! I can confirm that this one still works for 11.0 SP9 in a Windows 7 64bit environment.

**Comment by EliJDonahue** [comment]
Awesome! If you’d like to score an easy pull request for Hacktoberfest you can update the history section of the readme with the following changes:

* Remove “Unlike community projects that have been migrated and archived, this project will be updated for compatibility with the latest release of Aras Innovator.”
* Add Aras 11.0 SP9 to the supported versions table for release 9.3.

**Comment by EliJDonahue** [comment]
Closing issue since the project has been tested in Aras 11 SP9 and the documentation is updated.
